#!/bin/sh

outfile=$1
shift

if [ -z $outfile ]; then
	echo "Usage: pdfmerge <output.pdf> <input1.pdf> [input2.ps] .. [inputN.pdf]"
	exit 1;
fi


gs -dNOPAUSE -sDEVICE=pdfwrite -sOUTPUTFILE=$outfile -dBATCH $@
