#!/bin/sh 
#@author Eugene Tseytlin (University of Pittsburgh)


# do some parameter checking
PROG=`basename $0` 

if [ -z $1 ];
then
    echo "Usage: ${PROG} <dir1> [dir2] ... [dirN]" 
    echo "Rename diamond data to a unified directory structure"    
	exit 1
fi


for DIR in $@
do
	# convert to absolute path
	DIR=$(cd $DIR;pwd)
	DIR_NAME=$(basename $DIR)
	USERNAME=$(basename $DIR| awk -F '.' '{print $2}')
	
	echo "renaming $DIR_NAME ..."
	
	# renaming files
	for SD in $DIR/*
	do
		SF=$(basename $SD)
		SUBJECT="diamond_$USERNAME"
		FL=($SD/*.nii)
		if [ "${#FL[@]}" -eq 2 ]  && [[ ${FL[0]} == *"fieldmap"* ]]; then
			mv ${FL[0]} $SD/${SUBJECT}_${SF}_mag.nii 2> /dev/null	
			mv ${FL[1]} $SD/${SUBJECT}_${SF}_phase.nii 2> /dev/null
			mv "$(dirname ${FL[0]})/$(basename ${FL[0]} .nii).acpc.csv" $SD/${SUBJECT}_${SF}_mag.acpc.csv 2> /dev/null
			mv "$(dirname ${FL[1]})/$(basename ${FL[1]} .nii).acpc.csv" $SD/${SUBJECT}_${SF}_phase.acpc.csv 2> /dev/null
		elif [ "${#FL[@]}" -eq 1 ]; then
			mv ${FL[0]} $SD/${SUBJECT}_${SF}.nii 2> /dev/null
			mv "$(dirname ${FL[0]})/$(basename ${FL[0]} .nii).acpc.csv" $SD/${SUBJECT}_${SF}.acpc.csv 2> /dev/null
		elif [ "${#FL[@]}" -eq 3 ] && [[ ${FL[0]} == *"T1"* ]]; then
			mv ${FL[0]} $SD/${SUBJECT}_${SF}_crop.nii 2> /dev/null
			mv ${FL[1]} $SD/${SUBJECT}_${SF}_orient.nii 2> /dev/null
			mv ${FL[2]} $SD/${SUBJECT}_${SF}.nii 2> /dev/null
			
			mv "$(dirname ${FL[0]})/$(basename ${FL[0]} .nii).acpc.csv" $SD/${SUBJECT}_${SF}_crop.acpc.csv 2> /dev/null
			mv "$(dirname ${FL[1]})/$(basename ${FL[1]} .nii).acpc.csv" $SD/${SUBJECT}_${SF}_orient.acpc.csv 2> /dev/null
			mv "$(dirname ${FL[2]})/$(basename ${FL[2]} .nii).acpc.csv" $SD/${SUBJECT}_${SF}.acpc.csv 2> /dev/null
		else
			N=1
			for F in ${FL[@]}
			do 
				mv $F $SD/${SUBJECT}_${SF}.${N}.nii 2> /dev/null 
				mv "$(dirname ${F})/$(basename ${F} .nii).acpc.csv" $SD/${SUBJECT}_${SF}.${N}.acpc.csv 2> /dev/null
				N=$[$N + 1]
			done
		fi
		mv $SD/*_ref.hdr $SD/${SUBJECT}_${SF}_ref.hdr 2> /dev/null
		mv $SD/*_ref.img $SD/${SUBJECT}_${SF}_ref.img 2> /dev/null
		mv $SD/*MB.hdr $SD/${SUBJECT}_${SF}.hdr 2> /dev/null
		mv $SD/*MB.img $SD/${SUBJECT}_${SF}.img 2> /dev/null
		mv $SD/*_ref.mat $SD/${SUBJECT}_${SF}_ref.mat 2> /dev/null
		mv $SD/*MB.mat $SD/${SUBJECT}_${SF}.mat 2> /dev/null
		mv $SD/*_ref.acpc.csv $SD/${SUBJECT}_${SF}_ref.acpc.csv 2> /dev/null
		mv $SD/*MB.acpc.csv $SD/${SUBJECT}_${SF}.acpc.csv 2> /dev/null
		mv $SD/*.bvec $SD/${SUBJECT}_${SF}.bvec 2> /dev/null
		mv $SD/*.bval $SD/${SUBJECT}_${SF}.bval 2> /dev/null
		mv $SD/*.edat2 $SD/${SUBJECT}_${SF}_task.edat2 2> /dev/null
		mv $SD/*.edat $SD/${SUBJECT}_${SF}_task.edat 2> /dev/null
		mv $SD/*.txt $SD/${SUBJECT}_${SF}_task.txt 2> /dev/null
		mv $SD/*.ecg $SD/${SUBJECT}_${SF}.ecg 2> /dev/null
		mv $SD/*.ext $SD/${SUBJECT}_${SF}.ext 2> /dev/null
		mv $SD/*.puls $SD/${SUBJECT}_${SF}.puls 2> /dev/null
		mv $SD/*.resp $SD/${SUBJECT}_${SF}.resp 2> /dev/null
	done
	
	# print report
	#echo "  NIFTI image file report" 2>&1 | tee -a $LOG_FILE
	#echo "  ===================================" 2>&1 | tee -a $LOG_FILE
	#for FL  in $TARGET_DIR/*/*.nii; 
	#do 
	#		FN=$(basename $FL)
	#	DM=$(fslhd $FL | grep -E '^dim[1-4]' | awk -F ' ' '{print $2}' |  tr '\n' ' '); 
	#	echo -e "  $FN      \t$DM" 2>&1 | tee -a $LOG_FILE
	#done
	#echo "  ===================================" 2>&1 | tee -a $LOG_FILE
	chgrp -R phillips $DIR 2> /dev/null
	chmod -R 775 $DIR 2> /dev/null

done

exit 0
